name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "We love new ideas! Tell us what you'd like to see."
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like?
      placeholder: A clear description of the feature...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've considered?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Model Quality
        - Training
        - Inference
        - Documentation
        - Security
        - Multilingual
        - Other
    validations:
      required: true
